trigger:
  branches:
    include:
      - main  # Runs pipeline on changes in the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use a hosted agent

stages:
- stage: Deploy
  jobs:
  - job: DeployResources
    displayName: 'Deploy Azure Resources'
    steps:

    # ✅ Login to Azure using DevOps Service Connection
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure-DevOps-Connection'  # Your service connection name
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name MyResourceGroup --location eastus
          az keyvault create --name MyKeyVault12345 --resource-group MyResourceGroup --location eastus
