trigger:
  branches:
    include:
      - main  # Trigger pipeline when changes are pushed to 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted agent

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    
    # ✅ Install Node.js explicitly
    - task: UseNode@2  
      inputs:
        version: '18.x'  # Specify Node.js version

    # ✅ Verify Node.js version
    - script: |
        node --version
        npm --version
      displayName: 'Check Node.js and NPM Version'

    # ✅ Install dependencies (if package.json exists)
    - script: |
        npm install
      displayName: 'Install Dependencies'

    # ✅ Run build script (if applicable)
    - script: |
        npm run build
      displayName: 'Run Build Script'
      condition: succeeded()

    # ✅ Run tests (if applicable)
    - script: |
        npm test
      displayName: 'Run Tests'
      condition: succeeded()

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy Application'
    steps:
    
    # ✅ Log in to Azure using a service connection
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure-devops-rpp-testing'  # Replace with your service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      

