trigger:
  branches:
    include:
      - main  # Runs pipeline when code is pushed to 'main'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'  # Use a Microsoft-hosted agent
    steps:
    - checkout: self  # Checkout code from GitHub
    - task: UseNode@2  # If you're using a Node.js project
      inputs:
        version: '16.x'
    - script: npm install
      displayName: 'Install Dependencies'
    - script: npm run build
      displayName: 'Build Application'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'dist'
        artifactName: 'drop'  # Stores build artifacts for deployment

- stage: Deploy
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureWebApp@1  # Deploy to Azure App Service
      inputs:
        azureSubscription: '<your-service-connection-name>'
        appName: '<your-app-name>'
        package: '$(System.ArtifactsDirectory)/drop'
